import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";


import Nav from "./Compontents/Nav";
import Footer from "./Compontents/Footer";


// const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={" h-fit w-full max-w-[1920px]"}>
        {/* <Nav /> */}
        <div className="h-full w-full">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
